# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-06-11 19:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capital', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RCPortfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('principal_amount', models.DecimalField(decimal_places=2, default=1, max_digits=12, verbose_name='Principal')),
                ('open_amount', models.DecimalField(decimal_places=2, default=1, max_digits=12, verbose_name='Opening Amount')),
                ('closing_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Closing Amount')),
            ],
        ),
        migrations.RenameModel(
            old_name='ClientPortfolio',
            new_name='ClientsPort',
        ),
    ]
