# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-06-11 20:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='withdrawdate',
            field=models.DateField(default=datetime.datetime(2018, 7, 11, 20, 25, 24, 391005, tzinfo=utc)),
        ),
    ]
